# Generated by Django 5.0.6 on 2024-08-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_traditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traditions',
            old_name='description',
            new_name='t_description',
        ),
        migrations.RenameField(
            model_name='traditions',
            old_name='image',
            new_name='t_image',
        ),
        migrations.RenameField(
            model_name='traditions',
            old_name='name',
            new_name='t_name',
        ),
    ]
