# Generated by Django 5.0.6 on 2024-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_description_traditions_t_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('origin_year', models.IntegerField()),
                ('significance', models.TextField()),
                ('associated_festival', models.CharField(blank=True, max_length=255, null=True)),
                ('rituals', models.TextField()),
                ('trad_images', models.ImageField(blank=True, null=True, upload_to='tradition_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
