# Generated by Django 5.0.6 on 2024-08-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_prod_tradition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_tradition',
            name='associated_festival',
        ),
        migrations.RemoveField(
            model_name='prod_tradition',
            name='rituals',
        ),
    ]
