# Generated by Django 5.0.6 on 2024-08-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_prod_tradition_associated_festival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_tradition',
            name='meta_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prod_tradition',
            name='meta_keywords',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prod_tradition',
            name='meta_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prod_tradition',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default, 1=Hidden'),
        ),
        migrations.AddField(
            model_name='prod_tradition',
            name='tag',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prod_tradition',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
