# Generated by Django 5.0.6 on 2024-08-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_prod_tradition_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_tradition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.traditions'),
        ),
    ]
