# Generated by Django 5.0.6 on 2024-08-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_prod_tradition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_tradition',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.traditions'),
        ),
    ]
