# Generated by Django 5.0.6 on 2024-08-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_prod_tradition_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod_tradition',
            old_name='category',
            new_name='tradition',
        ),
    ]
