# Generated by Django 5.0.6 on 2024-08-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_category_prod_tradition_tradition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_tradition',
            name='tradition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.traditions'),
        ),
    ]
