# Generated by Django 5.0.6 on 2024-08-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_prod_tradition_tradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_tradition',
            name='slug',
            field=models.CharField(default='default-trad', max_length=150),
        ),
    ]
