# Generated by Django 5.0.6 on 2024-08-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_prod_tradition_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod_Tradition',
        ),
    ]
