# Generated by Django 5.0.6 on 2024-08-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_traditionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
    ]
